# Generated by Django 3.1.6 on 2021-03-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_auto_20210306_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listák',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Listák',
                'verbose_name_plural': 'Listáks',
            },
        ),
        migrations.DeleteModel(
            name='Lista',
        ),
    ]
