# Generated by Django 3.1.6 on 2021-03-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0003_auto_20210306_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listák',
            new_name='Lista',
        ),
        migrations.AlterModelOptions(
            name='lista',
            options={'verbose_name': 'Lista', 'verbose_name_plural': 'Lista'},
        ),
    ]
